-- Run in Supabase SQL Editor
ALTER TABLE trades ADD COLUMN IF NOT EXISTS lot_size DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS rule_split_entry BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS rule_sl_tp_set   BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS rule_chart_basis BOOLEAN NOT NULL DEFAULT TRUE;
